# Generated by Django 3.0.7 on 2020-07-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=60),
        ),
    ]
