# Generated by Django 3.0.7 on 2020-07-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0002_auto_20200703_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='location_id',
            new_name='location',
        ),
    ]
